"""
Streaming Query API route.
POST /api/v1/query/stream — dedicated SSE streaming endpoint for RAG queries.
"""

import json
from typing import Any, Dict

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse

from src.core.security import get_current_user, sanitize_query
from src.models.schemas import QueryStreamRequest
from src.controllers.rag_controller import get_rag_controller
from src.utils.logger.logger import get_logger

router = APIRouter(prefix="/query", tags=["Query"])
logger = get_logger(name="QueryStreamAPI")


@router.post("/stream")
async def query_rag_stream(
    request: QueryStreamRequest,
    user: dict = Depends(get_current_user),
):
    """
    Execute a RAG query with **Server-Sent Events (SSE)** streaming.

    Tokens are delivered in real-time as they are generated by the LLM.
    Self-RAG is disabled in streaming mode.

    **SSE format:**
    ```
    data: {"content": "token"}
    data: {"content": " another token"}
    data: [DONE]
    ```

    **Example (JavaScript):**
    ```javascript
    const response = await fetch('/api/v1/query/stream', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer <token>',
      },
      body: JSON.stringify({ query: 'What is RAG?' }),
    });

    const reader = response.body.getReader();
    const decoder = new TextDecoder();
    let answer = '';

    while (true) {
      const { done, value } = await reader.read();
      if (done) break;
      const text = decoder.decode(value, { stream: true });
      for (const line of text.split('\\n')) {
        if (line.startsWith('data: ') && line !== 'data: [DONE]') {
          const { content } = JSON.parse(line.slice(6));
          answer += content;
        }
      }
    }
    console.log(answer);
    ```

    **Example (curl):**
    ```bash
    curl -N -X POST http://localhost:8081/api/v1/query/stream \\
      -H "Content-Type: application/json" \\
      -H "Authorization: Bearer <token>" \\
      -d '{"query": "What is RAG?"}'
    ```
    """
    clean_query = sanitize_query(request.query)
    controller = get_rag_controller()

    def event_stream():
        try:
            for chunk in controller.query_stream(
                query=clean_query,
                filters=request.filters,
                user_id=user.get("sub"),
                org_id=user.get("org_id"),
                top_k=request.top_k,
                enable_hyde=request.enable_hyde,
                enable_reranking=request.enable_reranking,
            ):
                data = json.dumps({"content": chunk})
                yield f"data: {data}\n\n"
            yield "data: [DONE]\n\n"
        except Exception as e:
            logger.error(f"Streaming error: {e}")
            yield f"data: {json.dumps({'error': str(e)})}\n\n"
            yield "data: [DONE]\n\n"

    return StreamingResponse(
        event_stream(),
        media_type="text/event-stream",
        headers={
            "Cache-Control": "no-cache",
            "Connection": "keep-alive",
            "X-Accel-Buffering": "no",
        },
    )
